// The installable-web-app layer: manifest, icons and service worker.
//
// The game itself is untouched by any of this — it is still one self-contained page. These files
// only tell a phone that the page may live on the home screen, in landscape, without browser
// chrome, and still open with no network.
//
// They are generated, never committed (the icons are drawn by tools/icon.js, ARCHITECTURE section
// 0: zero binary assets). Two callers render the same bytes:
//   tools/build.js   writes them beside dist/index.html, which is what GitHub Pages publishes
//   tools/server.js  serves them from memory, so `npm run dev` behaves like the deployed site
// Dev serves DEV_SW instead of the real worker: a worker that caches would hand you yesterday's
// bundle on the next reload, which is the last thing a dev loop needs.
import crypto from 'node:crypto';
import { renderIcon } from './icon.js';

/** Icons the manifest advertises. 180 is Apple's home-screen size; 192/512 are Android's. */
export const ICONS = [
  { path: 'icons/icon-32.png', size: 32, purpose: 'any' },
  { path: 'icons/icon-180.png', size: 180, purpose: 'any' },
  { path: 'icons/icon-192.png', size: 192, purpose: 'any' },
  { path: 'icons/icon-512.png', size: 512, purpose: 'any' },
  { path: 'icons/icon-maskable-512.png', size: 512, purpose: 'maskable' },
];

export const MANIFEST_PATH = 'manifest.webmanifest';
export const SW_PATH = 'sw.js';

/**
 * Everything the page precaches, in the order the worker installs them. `index.html` is the whole
 * game, so an installed copy needs nothing else to run.
 */
export const PRECACHE = ['./index.html', './' + MANIFEST_PATH, ...ICONS.map((i) => './' + i.path)];

/**
 * The manifest. Every URL is relative: the site is published under a project path
 * (/aether-and-brass/), so an absolute "/" would scope the app to the wrong place.
 */
export function manifestJson() {
  return JSON.stringify({
    name: 'Aether & Brass',
    short_name: 'Aether & Brass',
    description: 'A steampunk high-fantasy side-scrolling beat-em-up, drawn and synthesized entirely in code.',
    id: './',
    start_url: './',
    scope: './',
    // Fullscreen where the platform allows it (Android), plain standalone where it does not (iOS).
    display: 'fullscreen',
    display_override: ['fullscreen', 'standalone'],
    // 640x360 is a landscape game; an installed copy should never be handed a portrait window.
    orientation: 'landscape',
    background_color: '#000000',
    theme_color: '#0b0710',
    categories: ['games', 'entertainment'],
    icons: ICONS.map((i) => ({
      src: i.path,
      sizes: `${i.size}x${i.size}`,
      type: 'image/png',
      purpose: i.purpose,
    })),
  }, null, 2) + '\n';
}

/**
 * The service worker. `version` names the cache, so a new build installs into a fresh one and the
 * activate step deletes every older cache.
 * @param {string} version
 */
export function swSource(version) {
  return `// Generated by tools/pwa.js — do not edit; edit that file.
// Cache-first over one fixed list, with no revalidation: the page IS the game, so an installed copy
// needs nothing else and opens instantly, offline, from whatever the installed version put in the
// cache. Updates ride the worker instead — the browser re-fetches this script on every navigation,
// a new build changes VERSION, and installing fills a fresh cache and drops the old one. Refreshing
// the page in the background as well would re-download two megabytes on every launch to arrive at
// bytes we already had.
const VERSION = ${JSON.stringify(version)};
const CACHE = 'aether-brass-' + VERSION;
const PRECACHE = ${JSON.stringify(PRECACHE)};
/** Navigations are all served from this one page, whatever path inside the scope they asked for. */
const SHELL = './index.html';

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  // Our own origin only. The signalling broker and the WebRTC peers are somebody else's (and not
  // HTTP at all), so they never reach this handler — but be explicit.
  const url = new URL(req.url);
  const root = new URL('./', self.registration.scope).pathname;
  if (url.origin !== self.location.origin || !url.pathname.startsWith(root)) return;
  // Any navigation inside the scope is this one page; anything else is asked for by name.
  const key = req.mode === 'navigate' ? SHELL : './' + url.pathname.slice(root.length);
  if (PRECACHE.indexOf(key) === -1) return; // not something we hold: straight to the network
  e.respondWith(caches.open(CACHE).then((c) => c.match(key)).then((hit) => hit || fetch(req)));
});
`;
}

/**
 * The dev worker: registers, has a fetch handler (so install prompts behave), caches nothing, and
 * clears any cache a previously visited production build left on localhost.
 */
export const DEV_SW = `// Dev worker (tools/pwa.js DEV_SW): never caches, so a reload always shows the file on disk.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) await caches.delete(key);
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', () => { /* straight to the network */ });
`;

/**
 * Render every generated file.
 * @param {Buffer|string} indexHtml the built page, which the cache version is derived from
 * @param {{dev?: boolean}} [opts] dev swaps in the non-caching worker
 * @returns {Map<string, Buffer>} path (relative to the site root) -> bytes
 */
export function pwaAssets(indexHtml, opts = {}) {
  const files = new Map();
  for (const icon of ICONS) files.set(icon.path, renderIcon(icon.size, { maskable: icon.purpose === 'maskable' }));
  files.set(MANIFEST_PATH, Buffer.from(manifestJson(), 'utf8'));
  // The version covers the page and every precached file, so any change to what is cached renames
  // the cache. The icons are deterministic, so an unchanged build keeps its version.
  const hash = crypto.createHash('sha256');
  hash.update(Buffer.isBuffer(indexHtml) ? indexHtml : Buffer.from(String(indexHtml), 'utf8'));
  for (const path of [MANIFEST_PATH, ...ICONS.map((i) => i.path)]) hash.update(files.get(path));
  const version = opts.dev ? 'dev' : hash.digest('hex').slice(0, 12);
  files.set(SW_PATH, Buffer.from(opts.dev ? DEV_SW : swSource(version), 'utf8'));
  return files;
}
